### ISSUE TITLE
SessionData corruption

### ISSUE THREAD

**Issue by nsvir** [ScilCoop/pasteque-android-closed#5]
How to:
- With a valid data update
- Open and go in a cash
- add a product
- leave the application
- kill it in the task manager
- restart the application
- A corrupted data toast must appear
- Enjoy <3

Hint: something should be wrong between Transaction's lifecycle and SessionData

Stack:
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	java.io.EOFException
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.DataInputStream.readByte(DataInputStream.java:77)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.nextTC(ObjectInputStream.java:505)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:752)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readFieldDescriptors(ObjectInputStream.java:909)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:1722)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1634)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:657)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1782)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readFieldValues(ObjectInputStream.java:1113)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:454)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1345)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at fr.pasteque.client.data.SessionData.loadSession(SessionData.java:71)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at fr.pasteque.client.data.DataLoader.loadAll(DataLoader.java:34)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at fr.pasteque.client.Start.onCreate(Start.java:83)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at android.app.Activity.performCreate(Activity.java:6374)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at android.app.ActivityThread.access$900(ActivityThread.java:181)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at android.os.Handler.dispatchMessage(Handler.java:102)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at android.os.Looper.loop(Looper.java:145)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at android.app.ActivityThread.main(ActivityThread.java:6134)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.lang.reflect.Method.invoke(Native Method)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at java.lang.reflect.Method.invoke(Method.java:372)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
15:56:00.928	30492	fr.pasteque.client	ERROR	Pasteque/Data	    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by nsvir** [comment]
Fixed https://github.com/ScilCoop/pasteque-android/commit/9d15dc617fe0ceffb87d0d678005dd01a95e5d6c

**Comment by nsvir** [comment]
Fixed https://github.com/ScilCoop/pasteque-android/commit/9d15dc617fe0ceffb87d0d678005dd01a95e5d6c
